# This is a basic workflow to help you get started with Actions

name: BASIC CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ hw1 ]
  pull_request:
    branches: [ hw1 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y clang-tidy
      - run: clang-tidy hw1_lib/*.c hw1_lib/*.h main.c -warnings-as-errors=* -extra-arg=-std=c99 -- -I hw1_lib/
  build:
    runs-on: ubuntu-latest
    needs: [check]
    steps:
    - uses: actions/checkout@v2 
    - run: sudo apt-get update -y
    - run: sudo snap install cmake --classic
    - run: mkdir build
    - run: ls
    - run: cat CMakelists.txt
    - run: cd build
    - run: sudo cmake ../
    - run: make
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: main.out
